### ISSUE TITLE
Are there any plans to support other mod loaders?

### ISSUE THREAD

**Issue by EvanHsieh0415** [Ewan-Selkirk/Dimension-Viewer#4]
like `Fabric`, `Quilt`, even `NeoForge`

**Comment by Ewan-Selkirk** [comment]
I think eventually I would like to try and do at least a Fabric port as I know Fabric is quite popular, but I think it would take me a while to actually implement as I have no idea how Fabric actually works.
I have also never heard of NeoForge and know basically nothing about Quilt but I will look into them.

I'll keep the issue open as a reminder for myself

**Comment by RTAkland** [comment]
maybe use TeamCommand's API? /team modify test suffix "this is suffix"

**Comment by RTAkland** [comment]
i made one: https://github.com/DangoTown/ViewDimension

**Comment by Ewan-Selkirk** [comment]
I know it's been over a year since this issue was made but I finally got round to learning how Fabric works and have now managed to port the mod over!
It currently only supports Minecraft version 1.21+ but I should be able to easily backport it to older versions (once I am no longer sick of looking at Java lmao)

Here's a [Modrinth link](https://modrinth.com/mod/dimension-viewer/version/2.0.0) and here's a [CurseForge link](https://www.curseforge.com/minecraft/mc-mods/dimension-viewer/files/5633137)

I also realised I never posted about porting to NeoForge, but that exists on the same pages as well

**Comment by RTAkland** [comment]
nice😁
